### Array Properties

In [1]:
import numpy as np

##### arr.shape check dimensions of exceltable or array

In [4]:
arr=np.array([[13,3,4,5],
              [2,3,4,5],
              [2,3,4,51]])
print(arr.shape)

(3, 4)


##### size Total no of elements in array

In [6]:
arr=np.array([[13,3,4,5],
              [2,3,4,5],
              [2,3,4,51]])
print(arr.size)

12


##### ndim check which dimensional array it is

In [7]:
arr_1d=np.array([13,3,4,5])
arr_2d=np.array([[13,3,4,5],
              [2,3,4,5],
              [2,3,4,51]])
arr_3d=np.array([
    [[13,3,4,5],[2,3,4,5],[2,3,4,51]],
    [[13,3,4,5],[2,3,4,5],[2,3,4,51]]
    ])

print(arr_1d.ndim)
print(arr_2d.ndim)
print(arr_3d.ndim)

1
2
3


##### arr.dtype check datatype of array

In [8]:
arr=np.array([13,3,4.5,5])
print(arr.dtype)


float64


##### astype(newtype) change datatype of  of array (if values in array are float then it will convert into int. decimal value got deleted)

In [11]:
arr=np.array([13,3,4.5,5])
print(arr.dtype)
int_arr=arr.astype(int)
print(int_arr)
print(int_arr.dtype)


float64
[13  3  4  5]
int64


### Array operation

##### Operator

In [14]:
arr=np.array([10,30,40,50])
print(arr+2)
print(arr*2)
print(arr**2)
print(arr//2) # floor value
print(arr%2) # Remainder
print(arr/2) # float
print(arr-2)

[12 32 42 52]
[ 20  60  80 100]
[ 100  900 1600 2500]
[ 5 15 20 25]
[0 0 0 0]
[ 5. 15. 20. 25.]
[ 8 28 38 48]


##### Aggregate Function

In [16]:
arr=np.array([10,30,40,50])
print(np.sum(arr))
print(np.mean(arr))
print(np.min(arr))
print(np.max(arr))
print(np.std(arr))
print(np.var(arr))

130
32.5
10
50
14.79019945774904
218.75


##### np.arange(num) n-1 tak array ban 
##### if you want to split the array (np.array_split(x,3)) then it split x range array  in to 3 sub array


In [21]:
import numpy as np
x = np.arange(8.0)
print(x)
np.array_split(x, 3)


[0. 1. 2. 3. 4. 5. 6. 7.]


[array([0., 1., 2.]), array([3., 4., 5.]), array([6., 7.])]