### Indexing


##### array[index] # 1d array
##### array[row,column] # 2d array

In [1]:
import numpy as np

In [5]:
arr=np.array([1,2,3,4,5])
print(arr[3]) # 4th element 
print(arr[-1]) # last Element

4
5


In [ ]:
print(arr[::-1]) # reverse list

[5 4 3 2 1]


### Slicing

##### arr[Start:stop:step] # Stop is Excluded
##### arr[Start:end] start to end-1

In [ ]:

arr=np.array([1,2,3,4,5])
print(arr[0:3:2]) 
print(arr[:3]) #index 0 to 2
print(arr[::2]) # every secound elment

print(arr[::-1]) # reverse of element
    




[1 3]


#### Fancy indexing (Selecting multiple elements at once)

In [12]:
arr=np.array([1,2,3,4,5,6])
print(arr[[0,2,4]]) # it create a copy no changes in original array


[1 3 5]


#### Filtering( Bolean masking ) (Means conditions )

In [15]:
arr=np.array([1,2,3,4,5,6])
print(arr[arr>2]) # all elements in array >2 are printed

[3 4 5 6]
