## Reshapeing

#### Reshaping-Change dimension of array without modifhy its data (ex 1d-> 2d) 
#### arr.reshape(rows,columns) specify new shape
#### if dimension matches

In [4]:
import numpy as np

In [6]:
arr=np.array([1,2,3,4,5,6,7,8])
new_arr=arr.reshape(2,4)
print(new_arr) # total elements are same

# it doesn't create  copy it gives view means it affect array

[[1 2 3 4]
 [5 6 7 8]]


### Flattening

#### .ravel()-> view 
#### .flatten()-> copy

In [ ]:
arr=np.array([[1,2,3,4],
              [5,6,7,8]])
print(arr.ravel()) # view
print(arr.flatten()) # flatten  no argument is passed inside() it return 1d array

[1 2 3 4 5 6 7 8]
[1 2 3 4 5 6 7 8]
