# Broadcasting & vectorisation

## broadcasting

##### Problem

if you have a list of prices and you want apply a discount of 10 % on every value

In [9]:
prices=[100,200,300]
discount=10 # 10%
final_prices=[]
for price in prices:
    final_price=price-((price*discount)//100)
    final_prices.append(final_price)
print(final_prices)

[90, 180, 270]


##### Solution Fast and reliable for large datasets use numpy arrays

In [10]:
import numpy as np
prices=np.array([100,200,300])
discount=10
final_prices=prices-((prices*discount)//100)
print(final_prices)

[ 90 180 270]


### single value

In [12]:
arr=np.array([100,200,300])
add_2=arr+2
print(add_2) # 2 is added in each value  of array

[102 202 302]


#### 1d_2d

In [15]:
matrix=np.array([[1,2,3],[4,5,6]])
vector=np.array([10,20,30])# Numpy expand array to Match dimension
print(np.shape(vector))
print(np.shape(matrix))

result=matrix+vector
print(result)




(3,)
(2, 3)
[[11 22 33]
 [14 25 36]]


#### Error by incomapatible dimension

In [22]:
arr1=np.array([[1,2,3],[4,5,6]])
arr2=np.array([1,2])
result=arr1+arr2
print(result)

## it throws an error 
# operands could not be broadcast together with shapes (2,3) (2,) 

ValueError: operands could not be broadcast together with shapes (2,3) (2,) 

## Vectoriztion
Writing operations without explicit Python loops, letting NumPy run them internally in optimized C code.

Makes code faster and shorter.

#### problem with for loop

In [23]:
l1=[1,2,3,4,5]
l2=[3,4,5,6,7]

output=[l1+l2 for l1,l2 in zip(l1,l2)]
print(output)

[4, 6, 8, 10, 12]


In [ ]:
A1=np.array([1,2,3,4,5])
A2=np.array([3,4,5,6,7])
result=A1+A2
print(result) # faster solution 


[ 4  6  8 10 12]


In [ ]:
AA=np.array([3,4,5,6,7])
print(AA*3) # easy way to perform operation

[ 9 12 15 18 21]


1. Concept

Vectorization → How operations are executed — replacing explicit loops with optimized NumPy operations.

Broadcasting → How NumPy automatically matches array shapes so the operation can happen.

2. Purpose

Vectorization → Makes code shorter, cleaner, and much faster by avoiding Python loops.

Broadcasting → Lets you work with arrays of different shapes without manually resizing them.

3. Analogy

Vectorization → You decide to use a high-speed blender instead of chopping veggies one by one with a knife.

Broadcasting → Your blender adjusts its jar size automatically to fit however many veggies you put in.

#### Feature             	Vectorization	                                    Broadcasting
#### What it is-	Performing operations without explicit loops     -	    Adjusting array shapes automatically
#### Focus-	        Speed and efficiency	   -                           Shape compatibility
#### Requires-	    Arrays of same shape (or scalars)	-               Arrays of compatible shapes per rules
#### When it happens-When you write math on whole arrays	-               Before the math happens, if shapes differ